### PR TITLE
Update driver to new vendor version 9.012.04

### PR DESCRIPTION
**Pull request by andrew64k**
minor HW version fix for irq_nvecs

### CODE REVIEW

**Comment by stormi** [comment]
Thanks for the PR. It looks good to me, but I also asked for a review by @tescande for a quick check of the updated sources (comparison with previous, and with upstream).

@andrew64k Could you describe the nature of the fix(es), to give us more context?

Regarding XCP-ng 8.2, as discussed earlier, the r8125-module package is now frozen, unless there are critical bugfixes with no risks for regression at all. But we could provide updated drivers as r8125-module-alt if necessary.

**Comment by andrew64k** [comment]
Realtek does not provide release notes. It's two fixes. One is a change to recognize chip versions >1 rather than ==2, I guess they may plan to release a v3 chip. The other is to be more dynamic on min_irq_nvecs.

**Comment by andrew64k** [comment]
I don't think an -alt package is a good idea for this fix. I think it's a worthwhile minor code fix for long term usage.
I think that if it passes your testing (as it passed mine), then the r8125 driver should just be updated.
At a minimum, the update should be added to the testing packages so it can be installed easily later.

If you are running a critical enterprise server then you are not using a r8125 NIC... It's used by the home lab/small user group.

**Comment by tescande** [comment]
Very light change in hw version detection. Looks good to me

**Review by tescande — APPROVED** [review]

**Comment by stormi** [comment]
> If you are running a critical enterprise server then you are not using a r8125 NIC... It's used by the home lab/small user group.

But if you are running a critical enterprise server you would like to avoid unnecessary updates to your LTS. That's a delicate balance, and I usually decide in favor of the option which causes the less disruption to the LTS.

**Comment by stormi** [comment]
> At a minimum, the update should be added to the testing packages so it can be installed easily later.

And the way we do this, for all other drivers for which we offer optional updates, is through an -alt package.

**Comment by stormi** [comment]
Koji build (v8.3-incoming): http://koji.xcp-ng.org/taskinfo?taskID=45313

**Comment by stormi** [comment]
Build `r8125-module-9.012.04-1.xcpng8.3` promoted to `v8.3-ci` to be included in the next CI run.

**Pull request merged**
